version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  frontend:
    container_name: react
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  backend:
    container_name: fastapi
    build:
      context: ./backend 
    ports:
      - "8000:8000"
    depends_on:
      - postgres